### ISSUE TITLE
What the fudge?

### ISSUE THREAD

**Issue by TheTemportalist** [BuiltBrokenModding/Mining101#1]
I love how there isn't any actual code, so I can't even see what this does :P

**Comment by Parker8283** [comment]
It does nothing yet. Just creating repos with the ideas.

**Comment by DarkGuardsman** [comment]
Essential yes, i created the repo with the intent to work on it. Right now its just a place holder for when i get around to updating my hand held mining laser.

**Comment by TheTemportalist** [comment]
Haha, I was just being silly. I read the short bio. :P
